version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#      KAFKA_NUM_PARTITIONS: 3

#   kafka2:
#     image: confluentinc/cp-kafka:latest
#     container_name: kafka2
#     restart: always
#     depends_on:
#       - zookeeper
#     ports:
#       - "9093:9093"
#     environment:
#       KAFKA_BROKER_ID: 2
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
# #      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
# #      KAFKA_NUM_PARTITIONS: 3

#   kafka3:
#     image: confluentinc/cp-kafka:latest
#     container_name: kafka3
#     restart: always
#     depends_on:
#       - zookeeper
#     ports:
#       - "9094:9094"
#     environment:
#       KAFKA_BROKER_ID: 3
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
#       KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
# #      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
# #      KAFKA_NUM_PARTITIONS: 3